import { Camera, Film, Users, Sparkles, Home, PartyPopper, Package, Zap } from "lucide-react"
import { editorialImages } from "@/lib/editorial-image-map"

export function getPackageSections() {
  const surfPackages = [
    {
      id: "wave-starter",
      name: "Wave Starter",
      price: "30€",
      duration: "30-45 min",
      icon: Camera,
      image: "/images/sports/female-surfer-golden-hour.jpg",
      features: [
        "30-45 min session (shore only)",
        "5 edited high-res surf shots",
        "Basic color correction",
        "Delivery same day",
      ],
      popular: false,
      color: "from-blue-500 to-cyan-500",
    },
    {
      id: "ride-session",
      name: "Ride Session",
      price: "70€",
      duration: "1-1.5 hours",
      icon: Film,
      image: "/images/sports/surf-wave-bw.jpg",
      features: [
        "1-1.5 hours shooting (shore)",
        "15 edited surf photos",
        "Short 20-30 sec highlight video",
        "Color corrected",
        "Delivery within 24h",
      ],
      popular: true,
      color: "from-purple-500 to-pink-500",
    },
    {
      id: "pro-wave-edit",
      name: "Pro Wave Edit",
      price: "100€-120€",
      duration: "2-3 hours",
      icon: Sparkles,
      image: "/images/sports/surf-powerful-wave.jpg",
      features: [
        "2-3 hour session (shore)",
        "30+ edited photos",
        "Full 1-2 min cinematic surf video",
        "Music + slow-mo + color grade",
        "Priority delivery (same day or next morning)",
      ],
      popular: false,
      color: "from-orange-500 to-red-500",
    },
    {
      id: "group-surf-pack",
      name: "Group Surf Pack",
      price: "From 100€",
      duration: "Group session",
      icon: Users,
      image: "/images/sports/surf-lineup-turquoise.jpg",
      features: [
        "For 2-5 surfers in one session",
        "10 edited photos per person",
        "Optional team highlight video",
        "Discount for groups",
        "From 20€ per person",
      ],
      popular: false,
      color: "from-green-500 to-teal-500",
    },
  ]

  const portraitPackages = [
    {
      id: "beach-portrait-mini",
      name: "Beach Portrait Mini",
      price: "30€",
      duration: "20 minutes",
      icon: Camera,
      image: "/images/portraits/woman-sunglasses-warm-light.jpg",
      features: ["20-minute shoot (after surf or sunset)", "5 edited portraits", "Natural light only"],
      popular: false,
      color: "from-pink-500 to-rose-500",
    },
    {
      id: "golden-hour-session",
      name: "Golden Hour Session",
      price: "50€",
      duration: "45 minutes",
      icon: Camera,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/BA9A3946-H0mbL25fuw7YkkBJ5cmFJNsNMRmT96.jpg",
      features: [
        "45-minute beach or village shoot",
        "10 edited portraits",
        "Color-graded for warm sunset tones",
        "Optional outfit change",
      ],
      popular: true,
      color: "from-amber-500 to-orange-500",
    },
    {
      id: "lifestyle-portrait-story",
      name: "Lifestyle Portrait Story",
      price: "80€-100€",
      duration: "1.5 hours",
      icon: Sparkles,
      image: "/images/portraits/stylized-portrait-sunglasses.jpg",
      features: [
        "1.5-hour creative session",
        "20+ edited photos",
        "You choose: beach, surfboard, or street style",
        "Includes artistic color grading + retouching",
      ],
      popular: false,
      color: "from-purple-500 to-indigo-500",
    },
  ]

  const comboPackages = [
    {
      id: "classic-combo",
      name: "The Classic Combo",
      price: "60€-70€",
      duration: "1.5 hours",
      icon: Camera,
      image: "/images/sports/surf-silhouette-sparkling.jpg",
      features: [
        "1.5-hour total (surf + mini portrait after)",
        "10 surf photos + 5 portraits",
        "Basic color correction",
        "Delivery in 24h",
      ],
      popular: false,
      color: "from-blue-500 to-purple-500",
    },
    {
      id: "ocean-story",
      name: "The Ocean Story",
      price: "100€-120€",
      duration: "2-2.5 hours",
      icon: Film,
      image: "/images/surfer-action.jpg",
      features: [
        "2-2.5 hours (surf session + lifestyle portraits)",
        "20+ edited photos",
        "Short highlight video (1 min)",
        "Both shore + portraits at golden hour",
      ],
      popular: true,
      color: "from-cyan-500 to-blue-500",
    },
    {
      id: "the-experience",
      name: "The Experience",
      price: "180€-250€",
      duration: "3-4 hours",
      icon: Sparkles,
      image: "/images/shop/sunset-couple-surfboards.jpg",
      features: [
        "3-4 hours full coverage (surf, water, portraits)",
        "40+ edited photos",
        "Cinematic video (1-2 min, graded + music)",
        "Private gallery delivery",
        "Option to include prints",
      ],
      popular: false,
      color: "from-red-500 to-pink-500",
    },
  ]

  const couplePackages = [
    {
      id: "romantic-couple-beach",
      name: "Romantic Beach Session",
      price: "100€",
      duration: "1 hour",
      icon: Camera,
      image: "/images/sunset-couple-silhouette.jpg",
      features: [
        "60-minute beach photoshoot",
        "10+ edited couple portraits",
        "Golden hour or sunset timing",
        "Natural romantic lighting",
        "Delivery in 24h",
      ],
      popular: false,
      color: "from-rose-500 to-pink-500",
    },
    {
      id: "couple-adventure-pack",
      name: "Couple Adventure Pack",
      price: "110€-130€",
      duration: "2 hours",
      icon: Film,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DSCF9743.JPG-LPk09NhFDupTAKYgXcanejoYJxQtXq.jpeg",
      features: [
        "2-hour creative couple session",
        "20+ edited romantic photos",
        "Multiple locations (beach, street, nature)",
        "Couple highlight video (30-45 sec)",
        "Artistic color grading",
        "Priority delivery (same day)",
      ],
      popular: true,
      color: "from-red-500 to-rose-500",
    },
    {
      id: "couple-engagement-premium",
      name: "Couple Engagement Premium",
      price: "180€-220€",
      duration: "3 hours",
      icon: Sparkles,
      image: "/images/surfer-wave-action.jpg",
      features: [
        "3-hour full couple photoshoot",
        "40+ professionally edited photos",
        "Engagement or anniversary focused",
        "Full cinematic video (1-2 min, music included)",
        "Premium album design included",
        "Private online gallery with unlimited downloads",
      ],
      popular: false,
      color: "from-purple-500 to-pink-500",
    },
  ]

  const realEstatePackages = [
    {
      id: "basic-listing",
      name: "Basic Listing Package",
      price: "100€",
      duration: "1 hour",
      icon: Home,
      image: "/images/real-estate/minimalist-bedroom-yellow-pillows.jpg",
      features: [
        "Interior + exterior coverage",
        "10-15 edited photos",
        "Professional color correction",
        "Fast turnaround (24-48h)",
      ],
      popular: false,
      color: "from-orange-500 to-amber-500",
    },
    {
      id: "premium-real-estate",
      name: "Premium Package",
      price: "150€",
      duration: "2 hours",
      icon: Sparkles,
      image: "/images/real-estate/rooftop-terrace-sunset-chairs.jpg",
      features: [
        "Wide-angle detailed coverage",
        "20+ edited images",
        "Twilight/golden hour shots available",
        "Priority editing and delivery",
      ],
      popular: true,
      color: "from-amber-500 to-yellow-500",
    },
  ]

  const eventPackages = [
    {
      id: "small-event",
      name: "Small Event",
      price: "80€",
      duration: "1 hour",
      icon: PartyPopper,
      image: "/images/events/nightclub-red.jpg",
      features: [
        "1 hour coverage",
        "30 edited high-res photos",
        "Key moments captured",
        "Online gallery delivery",
        "Fast turnaround (48h)",
      ],
      popular: false,
      color: "from-pink-500 to-purple-500",
    },
    {
      id: "half-day-event",
      name: "Half-Day Event",
      price: "150€",
      duration: "3 hours",
      icon: Camera,
      image: "/images/events/traditional-cultural-ensemble.jpg",
      features: [
        "3 hours full coverage",
        "60+ edited high-res photos",
        "Highlight selection",
        "Multiple angles captured",
        "Full color correction",
        "Priority delivery",
      ],
      popular: true,
      color: "from-purple-500 to-indigo-500",
    },
  ]

  const productPackages = [
    {
      id: "simple-pack",
      name: "Simple Pack",
      price: "25€",
      duration: "Per Product",
      icon: Package,
      image: "/images/product-nafa-single.jpg",
      features: [
        "3-5 high-res shots per product",
        "White or creative background",
        "Professional lighting setup",
        "E-commerce optimized",
      ],
      popular: false,
      color: "from-green-500 to-emerald-500",
    },
    {
      id: "brand-collection",
      name: "Brand Collection",
      price: "100€",
      duration: "Full Brand Session",
      icon: Sparkles,
      image: "/images/product-nafa-duo.jpg",
      features: [
        "Up to 5 products included",
        "20+ lifestyle/creative shots",
        "Social media ready sizes",
        "Brand style consistency",
      ],
      popular: true,
      color: "from-emerald-500 to-teal-500",
    },
  ]

  const automotivePackages = [
    {
      id: "automotive-signature-session",
      name: "Automotive Signature Session",
      price: "100€",
      duration: "1.5 hours",
      icon: Camera,
      image: "/images/pink-car-automotive.jpg",
      features: [
        "1.5-hour location shoot",
        "15 professionally edited vehicle photos",
        "Detail, interior, and exterior coverage",
        "Creative lighting and cinematic color grading",
        "Private online gallery delivered within 48h",
      ],
      popular: true,
      color: "from-fuchsia-500 to-purple-500",
    },
  ]

  const regularContentPackages = [
    {
      id: "content-starter",
      name: "Starter",
      price: "180€/month",
      duration: "1 content session/month",
      icon: Camera,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DSCF9002.JPG-m9r2NRLrWQXOrTVDZx1kLNmBHoJjiN.jpeg",
      features: ["Up to 2 hours shooting", "20 edited photos", "2 short-form vertical videos", "Professional color grading", "Social-media ready files", "Delivery within 3–4 days", "Equivalent to 90€/session"],
      popular: false,
      color: "from-sky-500 to-blue-600",
    },
    {
      id: "content-growth",
      name: "Growth",
      price: "320€/month",
      duration: "2 content sessions/month",
      icon: Sparkles,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/BA9A9229-RqQHgPv5SAZs8q2Sh2q2ZaP5oF1VCH.jpg",
      features: ["Up to 2 hours per session", "40 edited photos", "4 short-form vertical videos", "Professional color grading", "Basic retouching", "Social-media ready formats", "Priority delivery within 2–3 days", "Equivalent to 160€/session"],
      popular: true,
      color: "from-fuchsia-500 to-purple-600",
    },
    {
      id: "content-premium",
      name: "Premium",
      price: "550€/month",
      duration: "4 content sessions/month",
      icon: Zap,
      image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/DSCF9220.JPG-E5wL3GA0xvuhS6eEpkyQe6APAnwblV.jpeg",
      features: ["Up to 2 hours per session", "80+ edited photos", "6 short-form vertical videos", "Advanced color grading", "Professional retouching", "Multiple locations when practical", "Priority delivery within 48h", "Equivalent to 137.50€/session"],
      popular: false,
      color: "from-amber-500 to-orange-600",
    },
  ]

  const albumSections = [
    { id: "surf", eyebrow: "Surf", title: "Ocean in motion", description: "From first wave to full cinematic coverage, choose a session built around your time in the water.", image: editorialImages.hero.src, packages: surfPackages },
    { id: "portrait", eyebrow: "Portrait", title: "Your story, framed", description: "Natural light portraits with a streetwise, coastal point of view.", image: editorialImages.portraits.src, packages: portraitPackages },
    { id: "combo", eyebrow: "Surf + Portrait", title: "The whole day", description: "Pair the energy of the ocean with portraits that carry the feeling home.", image: "/images/shop/sunset-couple-surfboards.jpg", packages: comboPackages },
    { id: "couple", eyebrow: "Couple", title: "Two people, one story", description: "Romantic sessions made for beaches, streets, golden hours, and everything between.", image: "/images/sunset-couple-silhouette.jpg", packages: couplePackages },
    { id: "real-estate", eyebrow: "Real Estate & Rentals", title: "Make space memorable", description: "Bright, honest property imagery that helps guests and buyers picture themselves there.", image: "/images/real-estate/rooftop-terrace-sunset-chairs.jpg", packages: realEstatePackages },
    { id: "events", eyebrow: "Events", title: "Stay in the moment", description: "A focused visual record of the people, details, and energy that made your event matter.", image: "/images/events/nightclub-red.jpg", packages: eventPackages },
    { id: "product", eyebrow: "Product", title: "Objects with presence", description: "Clean, considered product photography for shops, launches, and social campaigns.", image: "/images/product-nafa-duo.jpg", packages: productPackages },
    { id: "content", eyebrow: "Regular Content", title: "Keep showing up", description: "Reliable monthly photography and short-form video for brands that need a consistent visual rhythm.", image: "/images/events/traditional-cultural-ensemble.jpg", packages: regularContentPackages },
    { id: "automotive", eyebrow: "Automotive", title: "Machines in motion", description: "Detail-led, cinematic coverage that turns your vehicle into a visual statement.", image: "/images/pink-car-automotive.jpg", packages: automotivePackages },
  ]

  return albumSections
}
